//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTXSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bed()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int BedID { get; set; }
        public int RoomID { get; set; }
        public int BedNumber { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
        public bool IsActive { get; set; }
        public bool Booking { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Room Room1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
